-- =============================================================================
-- 01_tariffs.sql  — GENERATED by db/seed/generate_seed.py. Do not edit by hand.
--
-- Source: Solar Report.xlsx, 'Solar Store Info' (Elec Zone / Tariff Rate / On-Peak).
--
-- off_peak_rate and demand_charge_rate are left NULL / 0 on purpose: the source
-- workbook publishes on-peak rates only. Fill them in from the official PEA and
-- MEA tariff announcements before trusting any TOU savings figure. A guessed
-- number here would corrupt every downstream financial report silently.
-- =============================================================================

INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('MEA 2.1.2', '2.1.2', 'MEA', 4.4217, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('MEA 3.2.2', '3.2.2', 'MEA', 4.1839, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('MEA 3.2.3', '3.2.3', 'MEA', 4.3297, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('PEA 2.1.1', '2.1.1', 'PEA', 3.9086, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('PEA 3.1.2', '3.1.2', 'PEA', 3.1471, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('PEA 3.2.2', '3.2.2', 'PEA', 4.1839, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('PEA 3.2.3', '3.2.3', 'PEA', 4.3297, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
INSERT INTO tariffs (tariff_name, tariff_code, utility, on_peak_rate, off_peak_rate, demand_charge_rate, effective_from)
VALUES ('PEA 8114', '8114', 'PEA', 6.8025, NULL, 0, DATE '2024-01-01')
ON CONFLICT (utility, tariff_code, effective_from) DO NOTHING;
