-- =============================================================================
-- 02_stores.sql  — GENERATED by db/seed/generate_seed.py. Do not edit by hand.
--
-- Source: Solar Report.xlsx, 'Solar Store Info' joined to 'Sheet13' on Name Code.
--
-- Coordinates come from Sheet13, NOT from the Info sheet: that sheet's Long
-- column holds a copy of Lat in every row. Stores with no Sheet13 entry are
-- loaded with NULL lat/lng and simply do not appear on the map until real
-- coordinates are supplied.
-- =============================================================================

INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('DC', 'Distribution Center', 'Warehouse', NULL,
        '889,889/1 Moo 3,Praksamai, Muang samutprakarn, Samut Prakan, Thailand.', 194.78, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '3.2.2' LIMIT 1),
        1, NULL, '2024-08-18',
        3964672.9, 277527.1, 4242200.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLBK', 'B105', 'Suan Bang Saeng Market, Khlong Bang Pla Kot', 'Samut Prakan',
        '131 หมู่ที่ 5 ตำบลในคลองบางปลากด อำเภอพระสมุทรเจดีย์ จังหวัดสมุทรปราการ รหัสไปรษณีย์ 10290', 55.68, 13.586463, 100.554984, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        1, NULL, '2023-06-29',
        1289556.07, 90268.92, 1379824.99)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLKB', 'B059', 'Private Land @Khubon 27,Bangkok', 'Bangkok',
        'เลขที่ 1 ซอยคู้บอน 27 แยก 17 แขวงท่าแร้ง เขตบางเขน กรุงเทพมหานคร 10220', 35.2, 13.860390, 100.665400, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        2, NULL, '2024-05-19',
        678385.5, 47486.99, 725872.49)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLBN', 'B056', 'Private Land @Soi Mahachai Bangna KM.10', 'Samut Prakan',
        'เลขที่ 59/11 หมู่ 13 ตำบลบางพลีใหญ่ อำเภอบางพลี จังหวัดสมุทรปราการ 10540', 35.5, 13.639230, 100.692000, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        2, NULL, '2024-05-13',
        678385.5, 47486.99, 725872.49)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLNT', 'BU65', 'Loeng Nok Tha,Yasothon', 'Yasothon',
        '147 , 147/1 , 147/3 หมู่ 1 ตำบลสามแยก อำเภอเลิงนกทา จังหวัดยโสธร 35120', 19.8, 16.208280, 104.552530, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        2, NULL, '2024-06-11',
        379509.0, 26565.63, 406074.63)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PRPT', 'BS54', 'RAWAI PHUKET', 'Phuket',
        '29/118 ม.2 ต.ราไวย์ อ.เมืองภูเก็ต จ.ภูเก็ต 83000', 48.4, 7.785010, 98.329430, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        902660.0, 63186.2, 965846.2)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBKP', 'BS62', 'Ban Kukoo , Phuket', 'Phuket',
        '19/59 ม.3 ต.รัษฎา อ.เมืองภูเก็ต จ.ภูเก็ต 83000', 39.6, 7.906890, 98.402840, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        738540.0, 51697.8, 790237.8)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTBR', 'BE73', 'Talad Klang BanChang', 'Rayong',
        'ม.5 ต.บ้านฉาง อ.บ้านฉาง จ.ระยอง 21130', 48.4, 12.727850, 101.063400, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        902660.0, 63186.2, 965846.2)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTAN', 'BC84', 'Takhli , Nakhon Sawan', 'Nakhon Sawan',
        '9/2 ถ.พระสังข์ ต.ตาคลี อ.ตาคลี จ.นครสวรรค์ 60140', 48.0, 15.263990, 100.347700, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        902660.0, 63186.2, 965846.2)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBSC', 'BE75', 'Baan Sanfun Suwinthawong', 'Chachoengsao',
        '43/14 ม.14 ต.ศาลาแดง อ.บางน้ำเปรี้ยว จ.ฉะเชิงเทรา 24000', 44.0, 13.795480, 100.942450, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        820600.0, 57442.0, 878042.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLPR', 'BE68', 'Lan-poon Market @ Rayong', 'Rayong',
        'เลขที่ 90/9 ถนนเนินพยอม ต.มาบตาพุด อ.เมืองระยอง จ.ระยอง 21150', 38.72, 12.724300, 101.170470, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        722128.0, 50548.96, 772676.96)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPYC', 'BE96', 'Plaeng Yao', 'Chachoengsao',
        'เลขที่ 71/4 หมู่ 3 ตำบลวังเย็น อำเภอแปลงยาว จังหวัดฉะเชิงเทรา รหัสไปรษณีย์ 24190', 48.4, 13.595570, 101.249490, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        902660.0, 63186.2, 965846.2)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBCP', 'BN60', 'Bueng Prachan', 'Phitsanulok',
        '99/225 ม.4 ต.วัดจันทร์ อ.เมืองพิษณุโลก จ.พิษณุโลก 65000', 48.4, 16.796640, 100.254810, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        3, NULL, '2024-12-23',
        787776.0, 55144.32, 842920.32)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBHK', 'U065', 'Baanphai บ้านไผ่ , ขอนแก่น', 'Khon Kaen',
        'เลขที่ 755/4 หมู่ 3 ถนนแจ้งสนิท (บ้านไผ่-บรบือ) ตำบลในเมือง อำเภอบ้านไผ่ จังหวัดขอนแก่น รหัสไปรษณีย์ 40110', 31.2, 16.057860, 102.732990, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTMC', 'BE88', 'Tha Mai , Chanthaburi ท่าใหม่ , จันทบุรี', 'Chanthaburi',
        'เลขที่ 8 ถนนเทศบาลสาย 9 ตำบลท่าใหม่ อำเภอท่าใหม่ จังหวัดจันทบุรี 22120', 31.2, 12.620100, 102.003480, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCYS', 'BS92', 'Chaiya , Surat Thani ไชยา , สุราษฎร์ธานี', 'Surat Thani',
        'เลขที่ 401 หมู่ 1 ตำบลตลาดไชยา อำเภอไชยา จังหวัดสุราษฎร์ธานี รหัสไปรษณีย์ 84110', 34.8, 9.386120, 99.203480, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKML', 'BC77', 'Khlong Thom 2 Market, Soi12 ตลาดคลองถม 2 , ซอย 12 , ลพบุรี', 'Lop Buri',
        '300/1 หมู่ที่ 7 ตำบลดีลัง อำเภอพัฒนานิคม ลพบุรี 15220', 31.0, 14.846120, 100.914660, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKYP', 'BS79', 'Khao Yoi , Phetchaburi เขาย้อย เพชรบุรี', 'Phetchaburi',
        'เลขที่ 4/5 หมู่ที่ 5 ตำบลเขาย้อย อำเภอเขาย้อย จังหวัดเพชรบุรี 76140', 31.2, 13.233340, 99.824420, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMWA', 'BN42', 'Mae Wang Market @ Amphoe Mae WangI อ.แม่วาง จังหวัดเชียงใหม่', 'Chiang Mai',
        'เลขที่ 497 หมู่ 5 ตำบลบ้านกาด อำเภอแม่วาง จังหวัดเชียงใหม่ 50360', 31.2, 18.602720, 98.828440, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '2.1.1' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMDS', 'B094', 'Soi Mangkhon Khan Di ซอยมังกรขันดี จ.สมุทรปราการ', 'Samut Prakan',
        'เลขที่ 261 หมู่ 5 ตำบลแพรกษา อำเภอเมืองสมุทรปราการ จังหวัดสมุทรปราการ 10280', 31.2, 13.587130, 100.657330, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPPN', 'BS80', 'Phrom Lok , Nakhon Si Thammarat พรหมโลก , นครศรีธรรมราช', 'Nakhon Si Thammarat',
        '246/21 หมู่ 1 ตำบลพรหมโลก อำเภอพรหมคีรี จังหวัดนครศรีธรรมราช 80320', 31.0, 8.524380, 99.823790, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPRS', 'U081', 'Prasat ปราสาท', 'Surin',
        'เลขที่ 586 หมู่ 2 ตำบลกังแอน อำเภอปราสาท จังหวัดสุรินทร์ รหัสไปรษณีย์ 32140', 31.2, 14.633455, 103.407359, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PRPF', 'BE67', 'Nikhom Pattana , Rayong นิคมพัฒนา ระยอง', 'Rayong',
        'เลขที่ 143 หมู่ 2 ตำบลมะขามคู่ อำเภอนิคมพัฒนา จังหวัดระยอง 21180', 34.8, 12.886390, 101.097890, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSOB', 'B097', 'Private Land @ Soi Onnuch 70/1 ซ.อ่อนนุช 70/1 กรุงเทพ', 'Bangkok',
        'เลขที่ 181 ซ.อ่อนนุช 70/1 แขวงประเวศ เขตประเวศ กรุงเทพ 10250', 34.8, 13.713840, 100.657810, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        4, NULL, '2025-01-31',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTBS', 'B096', 'THANON THANASIT, SOI BANGPLA 2 ถนนธนสิทธิ์ ซอยบางปลา2 จังหวัดสมุทรปราการ', 'Samut Prakan',
        'เลขที่ 168/9 หมู่ที่ 11 ตำบลบางปลา อำเภอบางพลี จังหวัดสมุทรปราการ 10540', 54.0, 13.589450, 100.722100, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '3.2.3' LIMIT 1),
        4, NULL, '2025-01-31',
        999000.0, 69930.0, 1068930.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTLN', 'BS75', 'Tha Sala , Nakhon Si Thammarat ท่าศาลา นครศรีธรรมราช', 'Nakhon Si Thammarat',
        'เลขที่ 461/57 หมู่ที่1 ตำบลท่าศาลา อำเภอท่าศาลา จังหวัดนครศรีธรรมราช 80160', 31.2, 8.667670, 99.923260, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTNN', 'BS74', 'Thanon Sai Thong, Pasemat , Narathiwat ถนนทรายทอง ปาเสมัส , นราธิวาส', 'Narathiwat',
        '245 ถนนทรายทอง 4 ตำบลสุไหงโก-ลก อำเภอสุไหงโก-ลก จังหวัดนราธิวาส 96120', 34.8, 6.031800, 101.969960, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWAS', 'U036', 'Wanon Niwat', 'Sakon Nakhon',
        '212 หมู่ 5 ตำบลวานรนิวาส อำเภอวานรนิวาส จังหวัดสกลนคร 47120', 31.2, 17.626620, 103.751150, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCMN', 'BE81', 'Chamchuri Market ตลาดจามจุรี', 'Nakhon Nayok',
        '3-523/32 ถนนชลประสิทธิ์ ตำบลนครนายก อำเภอเมืองนครนายก จังหวัดนครนายก 260000', 31.2, 14.197070, 101.216310, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBMS', 'S004', 'Baan Mae Nam, Koh Samui บ้านแม่น้ำ , เกาะสมุย', 'Surat Thani',
        'เลขที่ 46/4 หมู่ 4 ตำบลแม่น้ำ อำเภอเกาะสมุย จังหวัดสุราษฏร์ธานี รหัสไปรษณีย์ 84330', 34.8, 9.572800, 99.988000, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSRY', 'BC24', 'SIRANYA MARKET , LOPBURI ตลาดสิรัญญา จังหวัดลพบุรี', 'Lop Buri',
        '158 หมู่ที่ 2 ตำบลถนนใหญ่ อำเภอเมืองลพบุรี จังหวัดลพบุรี 15000', 31.2, 14.825100, 100.629530, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCSU', 'BU25', 'CHAREONSRI MARKET ตลาดเจริญศรี', 'Ubon Ratchathani',
        'อาคาร 5/1 ตลาดเจริญศรี เลขที่55/3 หมู่16 ตำบลแสนสุข อำเภอวารินชำราบ จังหวัดอุบลราชธานี 34190', 31.2, 15.172760, 104.873590, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPCL', 'BC87', 'Phothong Market Chaibadan ตลาดโพธิ์ทอง ชัยบาดาล', 'Lop Buri',
        '311 หมู่ 1 ตำบลชัยบาดาล อำเภอชัยบาดาล จังหวัดลพบุรี 15230', 36.08, 15.079570, 101.044670, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        4, NULL, '2025-01-31',
        722128.0, 50548.96, 772676.96)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSKN', 'BU86', 'Si-Khio , Korat (สีคิ้ว โคราช)', 'Nakhon Ratchasima',
        'เลขที่ 353 ตำบลสีคิ้ว อำเภอสีคิ้ว จังหวัดนครราชสีมา 30140', 31.46, 14.884100, 101.723540, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMYP', 'BE65', 'PRIVATE BUILDING @ APEC SQUARE MAB YANG PHON อาคารพาณิชย์ @ เอเปค สแควร์ มาบยางพร', 'Rayong',
        'เอเปกสแควร์ ซ.มาบยางพร 23 ห้วยแก้ว-ปรุมปราบ 4 ต.มาบยางพร อ.ปลวกแดง จ.ระยอง 21140', 31.46, 12.984840, 101.134120, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKKK', 'BU94', 'PRIVATE BUILDING @ KEHA KHON KAEN อาคารพาณิชย์ เคหะขอนแก่น', 'Khon Kaen',
        '398/3 ถนนกลางเมือง ตำบลในเมือง อำเภอเมืองขอนแก่น จังหวัดขอนแก่น 40000', 31.46, 16.399180, 102.831530, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMKS', 'BU75', 'PRIVATE BUILDING @ KALASIN อาคารพาณิชย์ อ.เมือง กาฬสินธุ์', 'Kalasin',
        '5/2 ถ. หน้าเรือนจำ ต.กาฬสินธุ์ อ.เมืองกาฬสินธุ์ จ.กาฬสินธุ์ 46000', 31.46, 16.443720, 103.515700, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PANC', 'B067', 'ANAMAI NGAM CHAREON ROAD , BANGKOK อนามัยงามเจริญ', 'Bangkok',
        'เลขที่ 414/2 ถนนอนามัยงามเจริญ แขวงท่าข้าม เขตบางขุนเทียน กรุงเทพมหานคร 10150', 31.46, 13.642690, 100.448600, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        5, NULL, '2025-02-28',
        577200.0, 40404.0, 617604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCPA', 'BU50', 'PRIVATE BUILDING @ CHUM PHAE DISTRICT อาคารพาณิชย์ อ.ชุมแพ', 'Khon Kaen',
        '711 หมู่ที่ 1 ต.ชุมแพ อ.ชุมแพ จ.ขอนแก่น 40130', 31.46, 16.538640, 102.099900, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKTD', 'B053', 'PRACHASAMAKKEE KRATINGDANG ซอยประชาสามัคคี (กระทิงเเดง)', 'Samut Prakan',
        'เลขที่ 765 หมูู่ 10 ถนนสุขสวัสดิ์-ประชาอุทิศคู่สร้าง ซอยประชาสามัคคี ตำบลในคลองบางปลากด อำเภอพระสมุทรเจดีย์ จังหวัดสมุทรปราการ 10290', 31.2, 13.593850, 100.516500, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PERL', 'BC90', 'Erawan Market ตลาดเอราวัณ , ลพบุรี', 'Lop Buri',
        'เลขที่ 168 ถนนนเรศวร (ช.2) ตำบลเขาสามยอด อำเภอเมืองลพบุรี จังหวัดลพบุรี รหัสไปรษณีย์ 15000', 31.46, 14.809300, 100.671100, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPKR', 'BW75', 'Pak Rat ปากแรต , ราชบุรี', 'Ratchaburi',
        'เลขที่ 146/1 ถนนบ้านปากแรต ตำบลบบ้านโป่ง อำเภอบ้านโป่ง จังหวัดราชบุรี รหัสไปรษณีย์ 70110', 31.46, 13.819120, 99.866870, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBNN', 'C012', 'Ban Na บ้านนา', 'Nakhon Nayok',
        'เลขที่ 358 หมู่ 10 ตำบลบ้านนา อำเภอบ้านนา จังหวัดนครนายก รหัสไปรษณีย์ 26110', 31.46, 14.258330, 101.075950, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        5, NULL, '2025-02-28',
        582010.0, 40740.7, 622750.7)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNSN', 'BS99', 'Narathiwat Stadium, Suriyapradit Road สนามกีฬานราธิวาส , ถนนสุริยะประดิษฐ์', 'Narathiwat',
        'เลขที่ 41/10 ถนนสุริยะประดิษฐ์ ตำบลบางนาค อำเภอเมืองนราธิวาส จังหวัดนราธิวาส รหัสไปรษณีย์ 96000', 30.5, 6.421090, 101.818550, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNBC', 'U054', 'Nong Bua Daeng , Chaiyaphum หนองบัวแดง . ชัยภูมิ', 'Chaiyaphum',
        '955 หมู่ที่ 9 ตำบลหนองบัวแดง อำเภอหนองบัวแดง จังหวัดชัยภูมิ รหัสไปรษณีย์ 36210', 30.5, 16.080440, 101.806890, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBBC', 'E008', 'Ban Bueng บ้านบึง', 'Chon Buri',
        'เลขที่ 128/2 ถนนชลบุรี-บ้านบึง ตำบลบ้านบึง อำเภอบ้านบึง จังหวัดชลบุรี รหัสไปรษณีย์ 20170', 35.38, 13.315280, 101.107220, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        643800.0, 45066.0, 688866.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTRN', 'C017', 'Tanon Rajdamnern (TonSon) ถนนราชดำเนิน (ต้นสน)', 'Nakhon Pathom',
        'เลขที่ 55 ถนนราชดำเนิน ตำบลพระปฐมเจดีย์ อำเภอเมืองนครปฐม จังหวัดนครปฐม รหัสไปรษณีย์ 73000', 30.5, 13.819580, 100.055460, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMAC', 'BN67', 'Mae Suai แม่สรวย', 'Chiang Rai',
        'เลขที่ 240 หมู่ 12 ตำบลแม่สรวย อำเภอแม่สรวย จังหวัดเชียงราย รหัสไปรษณีย์ 57180', 30.5, 19.655120, 99.539530, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNAS', 'S002', 'Na Thawi นาทวี', 'Songkhla',
        'เลขที่ 199/4 หมู่ 4 ตำบลนาทวี อำเภอนาทวี จังหวัดสงขลา รหัสไปรษณีย์ 90160', 30.5, 6.744310, 100.687500, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCAP', 'BW78', 'Cha-Am, Narathip Road ชะอำ , ถนนนราธิป', 'Phetchaburi',
        'เลขที่ 499/1 ถนนนราธิป ตำบลชะอำ อำเภอชะอำ จังหวัดเพชรบุรี รหัสไปรษณีย์ 76120', 30.5, 12.797280, 99.973190, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSGS', 'U095', 'Sangkha สังขะ', 'Surin',
        'เลขที่ 897 หมู่ 1 ตำบลสังขะ อำเภอสังขะ จังหวัดสุรินทร์ รหัสไปรษณีย์ 32150', 30.5, 14.642960, 103.849710, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCKN', 'BN68', 'Chiang Klang , Nan เชียงกลาง , น่าน', 'Nan',
        'เลขที่ 65/5 หมู่ 11 ตำบลเชียงกลาง อำเภอเชียงกลาง จังหวัดน่าน รหัสไปรษณีย์ 55160', 30.5, 19.289890, 100.861720, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCKK', 'BC94', 'CHAKUNGRAO ROAD ถนนชากังราว , กำแพงเพชร', 'Kamphaeng Phet',
        'เลขที่ 163/1 ถนนชากังราว ตำบลในเมือง อำเภอเมืองกำแพงเพชร จังหวัดกำแพงเพชร รหัสไปรษณีย์ 62000', 30.5, 16.487600, 99.532880, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKHP', 'BW80', 'Koh Lak เกาะหลัก', 'Prachuap Khiri Khan',
        'เลขที่ 189 ถนนเกาะหลัก ตำบลประจวบคีรีขันธ์ อำเภอเมืองประจวบคีรีขันธ์ จังหวัดประจวบคีรีขันธ์ รหัสไปรษณีย์ 77000', 30.5, 11.795860, 99.783170, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        6, NULL, '2025-06-01',
        503250.0, 35227.5, 538477.5)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMGN', NULL, 'Mueang Nan เมืองน่าน', NULL,
        'เลขที่ 41/8 ถนนผากอง ตำบลในเวียง อำเภอเมืองน่าน จังหวัดน่าน รหัสไปรษณีย์ 55000', 40.32, 18.781570, 100.775100, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.3' LIMIT 1),
        NULL, NULL, '2026-05-09',
        883000.0, 61810.0, 944810.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PRMB', NULL, 'Rat Phatthana Road, (Soi Mistine) ถ.ราษฎร์พัฒนา(ซอยมิสทีน)', NULL,
        'เลขที่ 227 ถนนราษฎร์พัฒนา แขวงราษฎร์พัฒนา เขตสะพานสูง กรุงเทพมหานคร รหัสไปรษณีย์ 10240', 37.18, 13.782242, 100.706175, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '3.2.3' LIMIT 1),
        7, NULL, '2026-01-27',
        747000.0, 52290.0, 799290.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPYB', NULL, 'Phahon Yothin 48 พหลโยธิน48', NULL,
        'เลขที่ 329/1 ซอยพหลโยธิน 48 แขวงอนุสาวรีย์ เขตบางเขน กรุงเทพมหานคร รหัสไปรษณีย์ 10220', 37.18, 13.876200, 100.618300, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        7, NULL, '2026-03-06',
        749000.0, 52430.0, 801430.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKKB', NULL, 'Krungthep Kreetha กรุงเทพกรีฑา', NULL,
        'เลขที่ 191 ถนนกรุงเทพกรีฑา แขวงทับช้าง เขตสะพานสูง กรุงเทพมหานคร รหัสไปรษณีย์ 10250', 37.18, 13.740400, 100.687800, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        7, 'atmoce', '2026-03-04',
        749000.0, 52430.0, 801430.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKRP', NULL, 'Khlong 11, Thanyaburi คลอง 11 , ธัญบุรี', NULL,
        'เลขที่ 120 หมู่ 1 ตำบลบึงน้ำรักษ์ อำเภอธัญบุรี จังหวัดปทุมธานี รหัสไปรษณีย์ 12110', 37.18, 14.060850, 100.849690, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-03-06',
        750000.0, 52500.0, 802500.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBYS', NULL, 'Bang Ya Praek , Samut Sakhon บางหญ้าแพรก , สมุทรสาคร', NULL,
        'เลขที่ 24/513 หมู่ 3 ตำบลบางหญ้าแพรก อำเภอเมืองสมุทรสาคร จังหวัดสมุทรสาคร รหัสไปรษณีย์ 74000', 37.18, 13.524575, 100.295371, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-03-11',
        750000.0, 52500.0, 802500.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPAM', NULL, 'PAI ปาย', NULL,
        'เลขที่ 1092 หมู่ 8 ตำบลเวียงใต้ อำเภอปาย จังหวัดแม่ฮ่องสอน รหัสไปรษณีย์ 58130', 37.18, 19.354900, 98.437900, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-11',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPAN', NULL, 'Phatthanakan Khukwang พัฒนาการคูขวาง', NULL,
        'เลขที่ 50/3 ถนนพัฒนาการคูขวาง ตำบลในเมือง อำเภอเมืองนครศรีธรรมราช จังหวัดนครศรีธรรมราช รหัสไปรษณีย์ 80000', 42.9, 8.414170, 99.975200, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-09',
        869300.0, 60851.0, 930151.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMKC', NULL, 'Mani Kaeo Village หมู่บ้านมณีแก้ว', NULL,
        'เลขที่ 127/43 หมู่ 1 ตำบลเหมือง อำเภอเมืองชลบุรี จังหวัดชลบุรี รหัสไปรษณีย์ 20130', 37.18, 13.277500, 100.957000, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-04-04',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMSK', NULL, 'Mooban Siwalee, Sri Chan Road หมู่บ้านสิวลี ถนนศรีจันทร์', NULL,
        'เลขที่ 507 หมู่ 14 ตำบลบ้านเป็ด อำเภอเมืองขอนแก่น จังหวัดขอนแก่น รหัสไปรษณีย์ 40000', 37.18, 16.438070, 102.784780, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-09',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNMR', NULL, 'Night Market ตลาดไนท์', NULL,
        'เลขที่ 681 หมู่ 17 ตำบลเหนือเมือง อำเภอเมืองร้อยเอ็ด จังหวัดร้อยเอ็ด รหัสไปรษณีย์ 45000', 37.18, 16.067510, 103.653600, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-09',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMIS', NULL, 'Makinta มากินตะ', NULL,
        'เลขที่ 520/1 ถนนธรรมนูญวิถี ตำบลหาดใหญ่ อำเภอหาดใหญ่ จังหวัดสงขลา รหัสไปรษณีย์ 90110', 42.9, 7.004990, 100.487330, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '8114' LIMIT 1),
        7, 'atmoce', '2026-05-10',
        869300.0, 60851.0, 930151.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPHC', NULL, 'Phanat Nikhom พนัสนิคม', NULL,
        'เลขที่ 219/3 ถนนเมืองเก่า ตำบลพนัสนิคม อำเภอพนัสนิคม จังหวัดชลบุรี รหัสไปรษณีย์ 20140', 37.18, 13.453360, 101.184300, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-04-04',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPSC', NULL, 'Phan Sadet Nai พันเสด็จใน , ชลบุรี', NULL,
        'เลขที่ 999/6 หมู่ 6 ตำบลบ่อวิน อำเภอศรีราชา จังหวัดชลบุรี รหัสไปรษณีย์ 20230', 37.18, 13.057870, 101.103100, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-04-04',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHNR', NULL, 'Hana, Nong Nam Yen @Sukhumvit54 , Rayong ฮานะ หนองน้ำเย็น @ สุขุมวิท 54 , ระยอง', NULL,
        'เลขที่ 98/19 ถนนคลองน้ำหู ตำบลเนินพระ อำเภอเมืองระยอง จังหวัดระยอง รหัสไปรษณีย์ 21000', 37.18, 12.684530, 101.186500, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-04-05',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNPC', NULL, 'Na Phrao นาพร้าว', NULL,
        'เลขที่ 555/12 หมู่ 7 ตำบลสุรศักดิ์ อำเภอศรีราชา จังหวัดชลบุรี รหัสไปรษณีย์ 20110', 40.04, 13.156350, 100.970440, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-04-02',
        811400.0, 56798.0, 868198.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHGS', NULL, 'Hin Kong หินกอง', NULL,
        'เลขที่ 22/3 หมู่ 1 ตำบลโคกแย้ อำเภอหนองแค จังหวัดสระบุรี รหัสไปรษณีย์ 18230', 40.04, 14.402800, 100.904000, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-11',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPTN', NULL, 'Prathai ประทาย , นครราชสีมา', NULL,
        'เลขที่ 94 หมู่ 14 ตำบลประทาย อำเภอประทาย จังหวัดนครราชสีมา รหัสไปรษณีย์ 30180', 37.18, 15.532550, 102.718650, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-08',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPMS', NULL, 'Phorkhuntale, Makham Tia พ่อขุนทะเล , ตำบลมะขามเตี้ย', NULL,
        'เลขที่ 91 หมู่ 3 ถนนพ่อขุนทะเล ตำบลมะขามเตี้ย อำเภอเมืองสุราษฎร์ธานี จังหวัดสุราษฎร์ธานี รหัสไปรษณีย์ 84000', 37.18, 9.088390, 99.325770, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-15',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMEN', NULL, 'Mae Phim Thong Market ตลาดแม่พิมทอง', NULL,
        'เลขที่ 9/29 ซอยเทศบาล 1 ถนนเทศบาล ตำบลโนนสูง อำเภอโนนสูง จังหวัดนครราชสีมา รหัสไปรษณีย์ 30160', 37.18, 15.176690, 102.250490, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-18',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNEC', NULL, 'Nong Ket Noi หนองเกตุน้อย', NULL,
        'เลขที่ 50/5 หมู่ 6 ตำบลหนองปลาไหล อำเภอบางละมุง จังหวัดชลบุรี รหัสไปรษณีย์ 20150', 37.18, 12.994640, 100.939980, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-01',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCBR', NULL, 'Chombueng จอมบึง', NULL,
        'เลขที่ 172 หมู่ 1 ตำบลจอมบึง อำเภอจอมบึง จังหวัดราชบุรี รหัสไปรษณีย์ 70150', 37.18, 13.621488, 99.604325, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-12',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPCC', NULL, 'Phaya Satcha Road ถนนพระยาสัจจา', NULL,
        'เลขที่ 83/88 หมู่ 3 ตำบลบ้านสวน อำเภอเมืองชลบุรี จังหวัดชลบุรี รหัสไปรษณีย์ 20000', 37.18, 13.350550, 100.974250, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.3' LIMIT 1),
        7, 'atmoce', '2026-04-30',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PYSP', NULL, 'Yeak Saeng Dao แยกแสงดาว', NULL,
        'เลขที่ 227 หมู่ 6 ตำบลปากโทก อำเภอเมืองพิษณุโลก จังหวัดพิษณุโลก รหัสไปรษณีย์ 65000', 34.32, 16.867980, 100.247820, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-10',
        741600.0, 51912.0, 793512.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBAS', NULL, 'Ban Mo บ้านหมอ', NULL,
        'เลขที่ 214 หมู่ 1 ตำบลบางโขมด อำเภอบ้านหมอ จังหวัดสระบุรี รหัสไปรษณีย์ 18130', 37.18, 14.608778, 100.736194, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-06',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPCN', NULL, 'Pak Thong Chai ปักธงชัย', NULL,
        'เลขที่ 188 หมู่ 12 ตำบลเมืองปัก อำเภอปักธงชัย จังหวัดนครราชสีมา รหัสไปรษณีย์ 30150', 42.9, 14.712500, 102.021700, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-20',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKON', NULL, 'Kham Thale So ขามทะเลสอ', NULL,
        'เลขที่ 656 หมู่ที่ 7 ตำบลขามทะเลสอ อำเภอขามทะเลสอ จังหวัดนครราชสีมา รหัสไปรษณีย์ 30280', 42.9, 14.955176, 101.950547, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-23',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTUS', NULL, 'Talad Yeak U-Ya ตลาดแยกอู่ยา', NULL,
        'เลขที่ 555 หมู่ที่ 1 ตำบลดอนกำยาน อำเภอเมืองสุพรรณบุรี จังหวัดสุพรรณบุรี รหัสไปรษณีย์ 72000', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-11',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKYS', NULL, 'Khirimat คีรีมาศ', NULL,
        'เลขที่ 132 หมู่ที่ 7 ตำบลโตนด อำเภอคีรีมาศ จังหวัดสุโขทัย รหัสไปรษณีย์ 64160', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-12',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PDIY', NULL, 'Kanchanaphisek 5/1 กาญจนาภิเษก 5/1', NULL,
        'เลขที่ 437/8 ถนนกาญจนาภิเษก แขวงหลักสอง เขตบางแค กรุงเทพมหานคร รหัสไปรษณีย์ 10160', 57.2, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'MEA' AND tariff_code = '2.1.2' LIMIT 1),
        7, 'atmoce', '2026-05-16',
        1236100.0, 86527.0, 1322627.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTPC', NULL, 'Talad Pimpa, Bang Pakong ตลาดพิมพา , บางปะกง', NULL,
        'เลขที่ 1/96 หมู่ที่ 2 ตำบลพิมพา อำเภอบางปะกง จังหวัดฉะเชิงเทรา รหัสไปรษณีย์ 24130', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-16',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPUN', NULL, 'Phutthamonthon Sai 7 พุทธมณฑล สาย 7', NULL,
        'เลขที่ 25/32 หมู่ที่ 2 ตำบลท่าตลาด อำเภอสามพราน จังหวัดนครปฐม รหัสไปรษณีย์ 73110', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-16',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHUN', NULL, 'Hua Thale (Phetlada Park) , Nakhon Ratchasima หัวทะเล เพชรลดา ปาร์ค', NULL,
        'เลขที่ 1147 หมู่ 8 ตำบลหนองบัวศาลา อำเภอเมืองนครราชสีมา จังหวัดนครราชสีมา รหัสไปรษณีย์ 30000', 40.04, 14.949660, 102.149810, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-05-26',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PDKP', NULL, 'Dok Khamtai ดอกคำใต้', NULL,
        'เลขที่ 186 หมู่ที่ 7 ตำบลดอกคำใต้ อำเภอดอกคำใต้ จังหวัดพะเยา รหัสไปรษณีย์ 56120', 37.18, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-28',
        753500.0, 52745.0, 806245.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMFC', NULL, 'Mae Fah Luang แม่ฟ้าหลวง', NULL,
        'เลขที่ 565 หมู่ที่ 2 ตำบลท่าสุด อำเภอเมืองเชียงราย จังหวัดเชียงราย รหัสไปรษณีย์ 57100', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-05-29',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTCL', NULL, 'Thale Chupsorn ทะเลชุบศร', NULL,
        'เลขที่ 98 ถนนพหลโยธิน (ช.15) ตำบลเขาสามยอด อำเภอเมืองลพบุรี จังหวัดลพบุรี รหัสไปรษณีย์ 15000', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '2.1.1' LIMIT 1),
        7, NULL, '2026-05-30',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKRC', NULL, 'Kad Sri Arun, San Kamphaeng กาดศรีอรุณ, สันกำแพง', NULL,
        'เลขที่ 117/52 หมู่ที่ 12 ตำบลสันกำแพง อำเภอสันกำแพง จังหวัดเชียงใหม่ รหัสไปรษณีย์ 50130', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-06',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPWK', NULL, 'Phu Wiang ภูเวียง', NULL,
        'เลขที่ 426 หมู่ 4 ตำบลภูเวียง อำเภอภูเวียง จังหวัดขอนแก่น รหัสไปรษณีย์ 40150', 37.18, 16.656260, 102.372270, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-06',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWNK', NULL, 'Waeng Noi แวงน้อย', NULL,
        'เลขที่ 654 หมู่ที่ 12 ตำบลแวงน้อย อำเภอแวงน้อย จังหวัดขอนแก่น รหัสไปรษณีย์ 40230', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-06',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKCC', NULL, 'Koh Chan เกาะจันทร์', NULL,
        'เลขที่ 167/7 หมู่ที่ 1 ตำบลเกาะจันทร์ อำเภอเกาะจันทร์ จังหวัดชลบุรี รหัสไปรษณีย์ 20240', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-06',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSTB', NULL, 'Satuek , Buri Ram สตึก , บุรีรัมย์', NULL,
        '55/1 หมู่ 16 ตำบลนิคม อำเภอสตึก จังหวัดบุรีรัมย์ รหัสไปรษณีย์ 31150', 42.9, 15.295980, 103.296830, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-10',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMSN', NULL, 'Mor Thor Sor Pratu 4 มทส.ประตู4', NULL,
        'เลขที่ 979 หมู่ที่ 5 ตำบลสุรนารี อำเภอเมืองนครราชสีมา จังหวัดนครราชสีมา รหัสไปรษณีย์ 30000', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-06-11',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNUU', NULL, 'Nah Ubon Ratchathani University หน้ามหาลัยอุบลราชธานี', NULL,
        'เลขที่ 182 หมู่ 3 ตำบลเมืองศรีไค อำเภอวารินชำราบ จังหวัดอุบลราชธานี รหัสไปรษณีย์ 34190', 34.32, 15.112382, 104.900505, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-06-13',
        741600.0, 51912.0, 793512.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNMK', NULL, 'Non Muang โนนม่วง', NULL,
        'เลขที่ 122 หมู่ 27 ตำบลศิลา อำเภอเมืองขอนแก่น จังหวัดขอนแก่น รหัสไปรษณีย์ 40000', 42.9, 16.489120, 102.819160, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-06-13',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSAR', NULL, 'Sarabuth Art Samart , Roi et อาจสามารถ , ร้อยเอ็ด', NULL,
        'เลขที่ 322 หมู่ 15 ตำบลอาจสามารถ อำเภออาจสามารถ จังหวัดร้อยเอ็ด รหัสไปรษณีย์ 45160', 40.04, 15.848250, 103.869670, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-15',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PDMK', NULL, 'Don Mong ดอนโมง', NULL,
        'เลขที่ 44 หมู่ที่ 10 ตำบลจระเข้ อำเภอหนองเรือ จังหวัดขอนแก่น รหัสไปรษณีย์ 40240', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '2.1.1' LIMIT 1),
        7, 'atmoce', '2026-06-16',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PDBC', NULL, 'Talad Bo Thong ตลาดบ่อทอง', NULL,
        'เลขที่ 88 หมู่ที่ 1 ถนนสุขพันธ์ถาวร 1 ตำบลบ่อทอง อำเภอบ่อทอง จังหวัดชลบุรี รหัสไปรษณีย์ 20270', 42.9, NULL, NULL, NULL,
        7, 'atmoce', '2026-06-17',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWTN', NULL, 'Wat That Market ตลาดวัดธาตุ', NULL,
        'เลขที่ 7 หมู่ 1 ตำบลหาดคำ อำเภอเมืองหนองคาย จังหวัดหนองคาย รหัสไปรษณีย์ 43000', 34.32, 17.899010, 102.770590, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-17',
        815500.0, 57085.0, 872585.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNGK', NULL, 'Nong Kae หนองแก', NULL,
        'เลขที่ 219 หมู่ที่ 11 ตำบลกุดกว้าง อำเภอหนองเรือ จังหวัดขอนแก่น รหัสไปรษณีย์ 40210', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-06-20',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPMT', NULL, 'Phothikit Saentung Market ตลาดโพธิกิจ แสนตุ้ง', NULL,
        'เลขที่ 345 หมู่ที่ 5 ตำบลแสนตุ้ง อำเภอเขาสมิง จังหวัดตราด รหัสไปรษณีย์ 23150', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-20',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLNK', NULL, 'Lao Nadi เหล่านาดี', NULL,
        'เลขที่ 536 หมู่ที่ 15 ตำบลบ้านเป็ด อำเภอเมืองขอนแก่น จังหวัดขอนแก่น รหัสไปรษณีย์ 40000', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, 'atmoce', '2026-06-22',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBAR', NULL, 'Na Mueang , Thanon Montri Suriyawong หน้าเมือง , ถนนมนตรีสุริยวงศ์', NULL,
        'เลขที่ 227/4 ถนนมนตรีสุริยวงศ์ ตำบลหน้าเมือง อำเภอเมืองราชบุรี จังหวัดราชบุรี รหัสไปรษณีย์ 70000', 42.9, NULL, NULL, NULL,
        7, 'atmoce', '2026-06-22',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSHA', NULL, 'Sawangha แสวงหา', NULL,
        'เลขที่ 140 หมู่ที่ 1 ตำบลแสวงหา อำเภอแสวงหา จังหวัดอ่างทอง รหัสไปรษณีย์ 14150', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-25',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWPR', NULL, 'Wat Phleng วัดเพลง', NULL,
        'เลขที่ 133 หมู่ที่ 5 ตำบลวัดเพลง อำเภอวัดเพลง จังหวัดราชบุรี รหัสไปรษณีย์ 70170', 42.9, NULL, NULL, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-27',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSUS', NULL, 'Sawankhalok สวรรคโลก', NULL,
        'เลขที่ 8/8 ซอย 1-7 , 9-10 ถนนศรีสัชนาลัย ตำบลเมืองสรรคโลก อำเภอสรรคโลก จังหวัดสุโขทัย รหัสไปรษณีย์ 64110', 40.04, 17.321700, 99.834800, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.1.2' LIMIT 1),
        7, NULL, '2026-06-30',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKPC', NULL, 'Ko Pho Road ถนนเกาะโพธิ์ , ชลบุรี', NULL,
        'เลขที่ 279/10 หมู่ 4 ถนนเกาะโพธิ์ - สามแยก ตำบลท่าบุญมี อำเภอเกาะจันทร์ จังหวัดชลบุรี รหัสไปรษณีย์ 20240', 37.18, 13.386560, 101.293090, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '8114' LIMIT 1),
        7, 'atmoce', '2026-06-30',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PRNC', NULL, 'Rai Nueng-Nong Kham ไร่หนึ่งหนองขาม', NULL,
        'เลขที่ 604/50 หมู่ 11 ตำบลหนองขาม อำเภอศรีราชา จังหวัดชลบุรี รหัสไปรษณีย์ 20230', 37.18, 13.102890, 100.969250, (SELECT tariff_id FROM tariffs WHERE utility = 'PEA' AND tariff_code = '3.2.2' LIMIT 1),
        7, NULL, '2026-06-30',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLSP', NULL, 'Lom Sak หล่มสัก', NULL,
        'เลขที่ 19/2 ถนนคชเสนีย์ ตำบลหล่มสัก อำเภอหล่มสัก จังหวัดเพชรบูรณ์ รหัสไปรษณีย์ 67110', 40.04, 16.780160, 101.241145, NULL,
        7, NULL, '2026-07-05',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSFS', NULL, 'Srifa Market, Koh Samui ตลาดสีฟ้า, เกาะสมุย', NULL,
        'เลขที่ 177/17 หมู่ 1 ตำบลตลิ่งงาม อำเภอเกาะสมุย จังหวัดสุราษฎร์ธานี รหัสไปรษณีย์ 84140', 42.9, 9.481100, 99.954900, NULL,
        7, NULL, '2026-07-05',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCTP', NULL, 'Chat Trakan ชาติตระการ', NULL,
        'เลขที่ 16 หมู่ที่ 5 ตำบลป่าแดง อำเภอชาติตระการ จังหวัดพิษณุโลก รหัสไปรษณีย์ 65170', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-06',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPKH', NULL, 'Pakham ปะคำ', NULL,
        'เลขที่ 257 หมู่ที่ 2 ตำบลปะคำ อำเภอปะคำ จังหวัดบุรีรัมย์ รหัสไปรษณีย์ 31220', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-06',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBUP', NULL, 'Bang Mun Nak บางมูลนาก', NULL,
        'เลขที่ 19 ถนนประเทืองถิ่น ตำบลบางมูลนาก อำเภอบางมูลนาก จังหวัดพิจิตร รหัสไปรษณีย์ 66120', 40.04, 16.024090, 100.375779, NULL,
        7, NULL, '2026-07-07',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPUP', NULL, 'Pak Phayun ปากพะยูน', NULL,
        'เลขที่ 879 หมู่ 1 ตำบลปากพะยูน อำเภอปากพะยูน จังหวัดพัทลุง รหัสไปรษณีย์ 93120', 42.9, 7.350000, 100.320790, NULL,
        7, NULL, '2026-07-09',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PRGN', NULL, 'Ra-ngae ระแงะ', NULL,
        'เลขที่ 60 หมู่ 7 ถนนเทศบาล 8 ตำบลตันหยงมัส อำเภอระแงะ จังหวัดนราธิวาส รหัสไปรษณีย์ 96130', 37.18, 6.292480, 101.710870, NULL,
        7, NULL, '2026-07-10',
        803500.0, 56245.0, 859745.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHHP', NULL, 'Hua Hin 102 หัวหิน 102', NULL,
        'เลขที่ 136/575 ซอยหมู่บ้านหนองแก ตำบลหนองแก อำเภอหัวหิน จังหวัดประจวบคีรีขันธ์ รหัสไปรษณีย์ 77110', 34.32, 12.545230, 99.955630, NULL,
        7, NULL, '2026-07-10',
        741600.0, 51912.0, 793512.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSIN', NULL, 'Sathing Phra , Songkhla สทิงพระ , สงขลา', NULL,
        'เลขที่ 10 หมู่ 4 ถนนเขาแดง-ระโนด ตำบลจะทิ้งพระ อำเภอสทิงพระ จังหวัดสงขลา รหัสไปรษณีย์ 90190', 40.04, 7.475450, 100.439180, NULL,
        7, NULL, '2026-07-11',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSHS', NULL, 'Singhanakhon สิงหนคร', NULL,
        'เลขที่ 287/29 หมู่ 5 ตำบลสทิงหม้อ อำเภอสิงหนคร จังหวัดสงขลา รหัสไปรษณีย์ 90280', 40.04, 7.233150, 100.556560, NULL,
        7, NULL, '2026-07-11',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPOC', NULL, 'Phrao พร้าว', NULL,
        'เลขที่ 9/1 หมู่ที่ 4 ตำบลเวียง อำเภอพร้าว จังหวัดเชียงใหม่ รหัสไปรษณีย์ 50190', 40.04, NULL, NULL, NULL,
        7, NULL, '2026-07-13',
        877200.0, 61404.0, 938604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCHC', NULL, 'Chiang Kham2 เชียงคำ 2', NULL,
        'เลขที่ 546 หมู่ที 4 ตำบลหย่วน อำเภอเชียงคำ จังหวัดพะเยา รหัสไปรษณีย์ 56110', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-13',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBDS', NULL, 'Ban Dan Lan Hoi บ้านด่านลานหอย', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-14',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTOS', NULL, 'Thanasarn Road ถนนธนสาร', NULL,
        'เลขที่ 570/1 ถนนธนสาร ตำบลในเมือง อำเภอเมืองสุรินทร์ จังหวัดสุรินทร์ รหัสไปรษณีย์ 32000', 40.04, 14.881043, 103.488910, NULL,
        7, NULL, '2026-07-15',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPDS', NULL, 'Padang Besar ปาดังเบซาร์', NULL,
        'เลขที่ 2 ถนนรอบเมือง ตำบลปาดังเบซาร์ อำเภอสะเดา จังหวัดสงขลา รหัสไปรษณีย์ 90240', 40.04, 6.670890, 100.323780, NULL,
        7, NULL, '2026-07-17',
        877200.0, 61404.0, 938604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCYR', NULL, 'Chumchon Phayoon ชุมชนพยูน', NULL,
        'เลขที่ 113/60 หมู่ที่ 5 ตำบลบ้านฉาง อำเภอบ้านฉาง จังหวัดระยอง รหัสไปรษณีย์ 21130', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-17',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNHB', NULL, 'Nong Hong หนองหงส์', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-18',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTKS', NULL, 'Thung Khok ทุ่งคอก', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-20',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PSRR', NULL, 'Suriyadetbamrung Road ถนนสุริยเดชบำรุง', NULL,
        'เลขที่ 83 หมู่ 20 ตำบลรอบเมือง อำเภอเมืองร้อยเอ็ด จังหวัดร้อยเอ็ด รหัสไปรษณีย์ 45000', 42.9, 16.040438, 103.655175, NULL,
        7, NULL, '2026-07-20',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHBR', NULL, 'Hemaraj Ban Khai เหมราช บ้านค่าย , ระยอง', NULL,
        'เลขที่ 1/19 หมู่ 11 ตำบลหนองละลอก อำเภอบ้านค่าย จังหวัดระยอง รหัสไปรษณีย์ 21120', 42.9, 12.827580, 101.233340, NULL,
        7, NULL, '2026-07-21',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKMC', NULL, 'Talad Pu Yai Kui, Soi Map Yai Lia28 ตลาดผู้ใหญ่กุ่ย, ซอยมาบยายเลีย 28', NULL,
        'เลขที่ 44/37 หมู่ 6 ตำบลหนองปรือ อำเภอบางละมุง จังหวัดชลบุรี รหัสไปรษณีย์ 20150', 40.04, 12.927879, 100.931866, NULL,
        7, NULL, '2026-07-22',
        877200.0, 61404.0, 938604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWPM', NULL, 'Wapi Pathum วาปีปทุม', NULL,
        'เลขที่ 523 หมู่ที่ 2 ตำบลหนองแสง อำเภอวาปีปทุม จังหวัดมหาสารคาม รหัสไปรษณีย์ 44120', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-23',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNGC', NULL, 'Na Kluea, Bang Lamung นาเกลือ, บางละมุง', NULL,
        'เลขที่ 115/47 หมู่ 5 ตำบลนาเกลือ อำเภอบางละมุง จังหวัดชลบุรี รหัสไปรษณีย์ 20150', 42.9, 12.966300, 100.898800, NULL,
        7, NULL, '2026-07-27',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPUC', NULL, 'Pak Nam Chumphon ปากน้ำชุมพร', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-07-27',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PMLC', NULL, 'Mae La-or Market ตลาดแม่ละออ', NULL,
        'เลขที่ 52/600 หมู่ 12 ตำบลหนองปรือ อำเภอบางละมุง จังหวัดชลบุรี รหัสไปรษณีย์ 20150', 40.04, 12.890344, 100.888611, NULL,
        7, NULL, '2026-07-27',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNTC', NULL, 'Nong Tamlueng (Pan Thong) หนองตำลึง (พานทอง)', NULL,
        'เลขที่ 83/3 หมู่ 6 ตำบลหนองตำลึง อำเภอพานทอง จังหวัดชลบุรี รหัสไปรษณีย์ 20160', 42.9, 13.416700, 101.070800, NULL,
        7, NULL, '2026-07-29',
        927000.0, 64890.0, 991890.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNKP', NULL, 'Nakhon Thai นครไทย', NULL,
        'เลขที่ 82 หมู่ 13 ตำบลนครไทย อำเภอนครไทย จังหวัดพิษณุโลก รหัสไปรษณีย์ 65120', 40.04, 17.091800, 100.830400, NULL,
        7, NULL, '2026-07-31',
        865200.0, 60564.0, 925764.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PNAC', NULL, 'Nikhom Nong - Kae นิคมหนองแก', NULL,
        'เลขที่ 222/500 หมู่ที่ 6 ตำบลมาบไผ่ อำเภอบ้านบึง จังหวัดชลบุรี รหัสไปรษณีย์ 20170', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-08-02',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PHYT', NULL, 'Huai Yot ห้วยยอด', NULL,
        'เลขที่ 778 ถนนเพชรเกษม ตำบลห้วยยอด อำเภอห้วยยอด จังหวัดตรัง รหัสไปรษณีย์ 92130', 42.9, NULL, NULL, NULL,
        7, NULL, '2026-08-02',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBTU', NULL, 'Buntharik บุณฑริก', NULL,
        'เลขที่ 231 หมู่ 2 ตำบลบัวงาม อำเภอบุณฑริก จังหวัดอุบลราชธานี รหัสไปรษณีย์ 34230', 43.5, 14.762100, 105.397500, NULL,
        7, NULL, '2026-08-02',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PLDS', NULL, 'Lamduan ลำดวน', NULL,
        'เลขที่ 27 หมู่ที่ 3 ตำบลลำดวน อำเภอลำดวน จังหวัดสุรินทร์ รหัสไปรษณีย์ 32220', 43.5, 14.724200, 103.667300, NULL,
        7, NULL, '2026-08-03',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPMP', NULL, 'PMT Rojana พีเอ็มที โรจนะ', NULL,
        'เลขที่ 63 หมู่ 4 ตำบลคุ้งลาน อำเภอบางปะอิน จังหวัดพระนครศรีอยุธยา รหัสไปรษณีย์ 13160', 43.5, 14.300800, 100.632500, NULL,
        7, NULL, '2026-08-03',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPHA', NULL, 'Phak Hai ผักไห่', NULL,
        'เลขที่ 295 หมู่ 4 ตำบลผักไห่ อำเภอผักไห่ จังหวัดพระนครศรีอยุธยา รหัสไปรษณีย์ 13120', 43.5, 14.458600, 100.367600, NULL,
        7, NULL, '2026-08-03',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PTWN', NULL, 'Tha Wang Pha ท่าวังผา', NULL,
        'เลขที่ 137 หมู่ 1 ตำบลท่าวังผา อำเภอท่าวังผา จังหวัดน่าน รหัสไปรษณีย์ 55140', 37.18, 19.093800, 100.804300, NULL,
        7, NULL, '2026-08-05',
        815500.0, 57085.0, 872585.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPKL', NULL, 'Phu Kradueng ภูกระดึง', NULL,
        'เลขที่ 91 หมู่ 8 ตำบลห้วยส้ม อำเภอภูกระดึง จังหวัดเลย รหัสไปรษณีย์ 42180', 43.5, 16.886760, 101.890400, NULL,
        7, NULL, '2026-08-05',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PDSL', NULL, 'Dan Sai ด่านซ้าย', NULL,
        'เลขที่ 341/32 หมู่ 3 ตำบลด่านซ้าย อำเภอด้านซ้าย จังหวัดเลย รหัสไปรษณีย์ 42120', 40.04, 17.272803, 101.151300, NULL,
        7, NULL, '2026-08-06',
        877200.0, 61404.0, 938604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPIU', NULL, 'Phichai พิชัย', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-08-08',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PPMN', NULL, 'Pump Ta Wan Market, Thung Song ตลาดปั๊มถาวร , ทุ่งสง', NULL,
        'เลขที่ 109 หมู่ 8 ตำบลชะมาย อำเภอทุ่งสง จังหวัดนครศรีธรรมราช รหัสไปรษณีย์ 80110', 34.32, 8.164280, 99.669950, NULL,
        7, NULL, '2026-08-08',
        753600.0, 52752.0, 806352.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PCYN', NULL, 'Chian Yai เชียรใหญ่', NULL,
        'เลขที่ 117/1 หมู่ที่ 3 ถนนสถลพลา ตำบลเชียรใหญ่ อำเภอเชียรใหญ่ จังหวัดนครศรีธรรมราช รหัสไปรษณีย์ 80190', 37.18, 8.175600, 100.145200, NULL,
        7, NULL, '2026-08-08',
        815500.0, 57085.0, 872585.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PKLS', NULL, 'Kong Krailat กงไกรลาศ', NULL,
        'เลขที่ 117/1 หมู่ 2 ตำบลบ้านกร่าง อำเภอกงไกรลาศ จังหวัดสุโขทัย รหัสไปรษณีย์ 64170', 43.5, 16.949700, 99.973500, NULL,
        7, NULL, '2026-08-09',
        952000.0, 66640.0, 1018640.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PWMS', NULL, 'Wang Muang วังม่วง', NULL,
        'เลขที่ 155/1 หมู่ที่ 9 ตำบลคำพราน อำเภอวังม่วง จังหวัดสระบุรี รหัสไปรษณีย์ 18220', 40.04, 14.841500, 101.128900, NULL,
        7, NULL, '2026-08-10',
        877200.0, 61404.0, 938604.0)
ON CONFLICT (store_code) DO NOTHING;
INSERT INTO stores (store_code, retail_store_code, store_name, province,
                    address, installed_kwp, lat, lng, tariff_id,
                    rollout_phase, monitoring_source, commissioned_at,
                    capex_before_vat, capex_vat, capex_net)
VALUES ('PBKK', NULL, 'Bueng Kaen Nakhon บึงแก่นนคร', NULL,
        NULL, 42.9, NULL, NULL, NULL,
        7, NULL, '2026-08-12',
        939000.0, 65730.0, 1004730.0)
ON CONFLICT (store_code) DO NOTHING;
